import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import React from "react";
import { ClerkProvider } from "@clerk/nextjs";
import Theme from "@/context/ThemeProvider";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  weight: ["300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider
      appearance={{
        variables: {
          colorPrimary: "#FC4747",
          colorBackground: "#161D2F",
          colorText: "#FFFFFF",
          colorTextSecondary: "#FFFFFF",
        },
        elements: {
          formFieldInput:
            "bg-transparent text-[#5A698F] focus:outline-none border-bottom border-[#5A698F] focus:border-[#5A698F]",
          formFieldLabel: "text-[#5A698F]",
        },
      }}
    >
      <html lang="en" suppressHydrationWarning>
        <body
          className={`min-h-screen w-screen max-w-full md:p-6 lg:p-8 ${inter.className}`}
        >
          <Theme>{children}</Theme>
        </body>
      </html>
    </ClerkProvider>
  );
}
